class UserAlreadyExistsError(Exception):
    """Exception which raised when user with given login is already saved"""
